#!/bin/sh

FILE=`zenity --file-selection --directory --title="Ordner wählen"`

case $? in
    0)
        cd $FILE
        git clone https://gist.github.com/91e593dcb595d427c7202de6abd1ecb6.git tmp
        mv tmp/package.json .
        rm -rf tmp
        (
            echo "10"
            echo "# download gulpfile"
            npm run download-gulpfile

            echo "20"
            echo "# download editorconfig"
            npm run download-editorconfig
            
            echo "30"
            echo "# download kirby plainkit"
            npm run download-kirby
            
            echo "50"
            echo "# creating directories"
            npm run create-dirs
        ) | zenity --progress --title="Kirby wird installiert" --text="lade Daten herunter …" --percentage=0 --auto-close

        npm install | zenity --progress --title="Kirby wird installiert" --text="lade npm Module …" --pulsate --auto-close
        
        zenity --info --text="Downloads abgeschlossen. Führe \"npm start\" aus um Server und Gulp-Task zu starten." --title="Fertig"
        ;;
    -1)
        zenity --info --text="Ein unerwarteter Fehler ist aufgetreten." --title="Fehler";;
esac
